In [1]:
import torch

In [30]:
x = torch.empty(3,2,dtype=torch.int16)
x1 = torch.rand(3,2)
x3 = torch.tensor([[3,5,7],[5,6,4]])

#adding x to x1
x1.add_(x)

print(x,'\n',x1,'\n',x3,"\nAdding two tensors\n1.",x1+x,'\n2.',torch.add(x1,x),'\n3.',x1)

tensor([[13936, 11913],
        [30972,     0],
        [   81,     0]], dtype=torch.int16) 
 tensor([[1.3936e+04, 1.1914e+04],
        [3.0973e+04, 5.4694e-02],
        [8.1282e+01, 6.4663e-01]]) 
 tensor([[3, 5, 7],
        [5, 6, 4]]) 
Adding two tensors
1. tensor([[2.7872e+04, 2.3827e+04],
        [6.1945e+04, 5.4694e-02],
        [1.6228e+02, 6.4663e-01]]) 
2. tensor([[2.7872e+04, 2.3827e+04],
        [6.1945e+04, 5.4694e-02],
        [1.6228e+02, 6.4663e-01]]) 
3. tensor([[1.3936e+04, 1.1914e+04],
        [3.0973e+04, 5.4694e-02],
        [8.1282e+01, 6.4663e-01]])


In [35]:
# To print
x[2,0].item()

81